INSERT INTO course (id, name, location) VALUES (1, 'The Sand Trap','Ship Bottom, LBI');
INSERT INTO course (id, name, location) VALUES (2, 'Seaport Village','Castaway Cove, Ocean City');
INSERT INTO course (id, name, location) VALUES (3, 'Island Golf', 'Surf CIty, LBI');

insert into hole(id, course_id, hole_number, par) values (1,1,1,3);
insert into hole(id, course_id, hole_number, par) values (2, 1,2,2);
insert into hole(id, course_id, hole_number, par) values (3, 1,3,2);
insert into hole(id, course_id, hole_number, par) values (4, 1,4,3);
insert into hole(id, course_id, hole_number, par) values (5, 1,5,2);
insert into hole(id, course_id, hole_number, par) values (6, 1,6,3);
insert into hole(id, course_id, hole_number, par) values (7, 1,7,2);
insert into hole(id, course_id, hole_number, par) values (8, 1,8,2);
insert into hole(id, course_id, hole_number, par) values (9, 1,9,2);
insert into hole(id, course_id, hole_number, par) values (11, 1,11,2);
insert into hole(id, course_id, hole_number, par) values (12, 1,12,4);
insert into hole(id, course_id, hole_number, par) values (13, 1,13,3);
insert into hole(id, course_id, hole_number, par) values (14, 1,14,2);
insert into hole(id, course_id, hole_number, par) values (15, 1,15,2);
insert into hole(id, course_id, hole_number, par) values (16, 1,16,4);
insert into hole(id, course_id, hole_number, par) values (17, 1,17,2);
insert into hole(id, course_id, hole_number, par) values (18, 1,18,2);
insert into hole(id, course_id, hole_number, par) values (10, 1,10,3);

insert into hole(id, course_id, hole_number, par) values (21, 2,1,2);
insert into hole(id, course_id, hole_number, par) values (22, 2,2,2);
insert into hole(id, course_id, hole_number, par) values (23, 2,3,2);
insert into hole(id, course_id, hole_number, par) values (24, 2,4,2);
insert into hole(id, course_id, hole_number, par) values (25, 2,5,2);
insert into hole(id, course_id, hole_number, par) values (26, 2,6,3);
insert into hole(id, course_id, hole_number, par) values (27, 2,7,3);
insert into hole(id, course_id, hole_number, par) values (28, 2,8,3);
insert into hole(id, course_id, hole_number, par) values (29, 2,9,3);
insert into hole(id, course_id, hole_number, par) values (31, 2,11,3);
insert into hole(id, course_id, hole_number, par) values (32, 2,12,2);
insert into hole(id, course_id, hole_number, par) values (33, 2,13,3);
insert into hole(id, course_id, hole_number, par) values (34, 2,14,3);
insert into hole(id, course_id, hole_number, par) values (35, 2,15,2);
insert into hole(id, course_id, hole_number, par) values (36, 2,16,2);
insert into hole(id, course_id, hole_number, par) values (37, 2,17,3);
insert into hole(id, course_id, hole_number, par) values (38, 2,18,2);
insert into hole(id, course_id, hole_number, par) values (39, 2,10,2);
